name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install pre-reqs
        shell: bash
        run: |
          npm ci
      
      - name: Build the output for MacOS
        shell: bash
        run: |
          npm run make

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: OhanaDeviceLogsViewer-build.${{ github.run_number }}
          tag: "build.${{ github.run_number }}"
          artifacts: "out/*.zip"
          draft: true
          commit: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
